### ISSUE TITLE
9.19.1: drbd_buildtag.sh relies on .git

### ISSUE THREAD

**Issue by jpds** [LINBIT/drbd-utils#13]
The `drbd_buildtag.sh` script relies on `.git` existing:

```
$ git version
git version 2.32.0
$ cd user/shared/
$ ./drbd_buildtag.sh drbd_buildtag.h
+ calldir=/home/buildd/tmp-drbd/drbd-utils-9.19.1/user/shared
+++ dirname ./drbd_buildtag.sh
++ cd .
++ pwd -P
+ cd /home/buildd/tmp-drbd/drbd-utils-9.19.1/user/shared
+ [[ drbd_buildtag.h =~ drbd_buildtag\.h$ ]]
+ drbd_buildtag_h /home/buildd/tmp-drbd/drbd-utils-9.19.1/user/shared/drbd_buildtag.h
+ local out=/home/buildd/tmp-drbd/drbd-utils-9.19.1/user/shared/drbd_buildtag.h
+ set -e
+ exec
+ echo -e '/* automatically generated. DO NOT EDIT. */'
+ test -e ../../.git
+ test -e /home/buildd/tmp-drbd/drbd-utils-9.19.1/user/shared/drbd_buildtag.h
+ echo '/home/buildd/tmp-drbd/drbd-utils-9.19.1/user/shared/drbd_buildtag.h not found.'
/home/buildd/tmp-drbd/drbd-utils-9.19.1/user/shared/drbd_buildtag.h not found.
+ test -e ../../.git
+ 'Install git and try again.'
./drbd_buildtag.sh: line 20: Install git and try again.: command not found
+ echo 'Your DRBD source tree is broken. Unpack again.'
Your DRBD source tree is broken. Unpack again.
+ exit 1
```

However the tarball that ships at https://github.com/LINBIT/drbd-utils/releases/tag/v9.19.1 on GitHub does not come with a `.git`.

**Comment by rck** [comment]
please read and understand this part of the README: https://github.com/LINBIT/drbd-utils#releases

use a release tarball from linbit.com, or a proper `git clone --recursive` from git

**Comment by jpds** [comment]
I had read that before this, went to https://linbit.com/drbd-user-guide/drbd-guide-9_0-en/#s-from-source which then goes to a page that 404s as it has a trialing string at the end of the URL - which is why I then downloaded the GitHub tarball!

**Comment by rck** [comment]
the one in the README should work, I will update the one in the documentation
