### ISSUE TITLE
user/drbdmon/Makefile.in: --pedantic-errors should be -pedantic-errors

### ISSUE THREAD

**Issue by AndrewV666** [LINBIT/drbd-utils#17]
In user/drbdmon/Makefile.in: CXXFLAGS=-std=c++11 -I. -I../shared -Icppdsaext/src -Wall -Werror **--pedantic-errors** -fPIC -O2 \ 

But according to "man gcc | fgrep pedantic-errors":
           -fsyntax-only  -fmax-errors=n  -Wpedantic **-pedantic-errors** -w
      **-pedantic-errors**
           error by **-pedantic-errors**.
(one dash).

GCC admits the "--pedantic-errors" form, some other compilers not.
Please, change this option to "-pedantic-errors".

**Comment by rck** [comment]
fixed in https://github.com/LINBIT/drbd-utils/commit/64900ddc7b5c7b29de200705242ca66df384a986
