### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by vivienne-wen** [LINBIT/drbd-utils#19]
There are some spelling mistakes in line 120 of the code
```
re_init_daemon()
{
	resources_with_existing_attributes=$( list_existing_attributes )
	resources_known_to_drbdadm=$( drbadm sh-resources )
	resources_seen_in_initial_dump=''
	status_delay=''
	exec 0< <(exec drbdsetup events2 --timestamps 9>&- )
}
```
The correct spelling is as follow：
resources_known_to_drbdadm=$( drbdadm sh-resources )

**Comment by rck** [comment]
Thanks, I'm pretty sure this is a bug, I created an internal MR fixing this. There will be a dot-release of drbd-utils later this week anyways, it should also then contain a fixed version.

**Comment by rck** [comment]
https://github.com/LINBIT/drbd-utils/commit/27678591e30f62c84269cef42ace7f0d6ecdc66c
