### ISSUE TITLE
Split-brain notification script not working

### ISSUE THREAD

**Issue by miro-igov** [LINBIT/drbd-utils#20]
Hello, 
notify-split-brain.sh is not sending email when SB occurs. There is missing environment variable $DRBD_PEER

From syslog:

notify-split-brain.sh[16322]: Environment variable $DRBD_PEER not found (this is normally passed in by drbdadm)

**Comment by rck** [comment]
Sorry for the long delay. AFAIK setting this environment variable was already deprecated with 8.3, and 9.0 finally stopped exposing it. I'd assume that this never worked with DRBD9. 

So long story short: thanks for reporting, I assume this needs some refactoring in all the scripts that are supposed to work with DRBD9, that don't already have fallbacks for finding the peer via "something else".

**Comment by rck** [comment]
This should be fixed now. You can test by just overwriting the script, or you can wait for 9.21.0-rc.1, which should be out today or tomorrow.

https://github.com/LINBIT/drbd-utils/commit/81aa507659fa47fdd8232e49368fd59e2a82aae5
