### ISSUE TITLE
Any support for a cpu mask string larger than 32 bytes?

### ISSUE THREAD

**Issue by cbf123** [LINBIT/drbd-utils#27]
The existing 32-byte CPU mask string effectively limits the user to being able to specify cpus 0-111.   Systems are getting large enough that they can now have more than 112 CPUs.

Are there any plans to increase the allowable size of the CPU mask string to something larger?

**Comment by JoelColledge** [comment]
It is correct that the 32-byte string is limiting. However, the limits are not quite that tight. The CPU mask string is passed into [bitmap_parse()](https://www.kernel.org/doc/html/latest/core-api/kernel-api.html#c.bitmap_parse). This allows CPU masks such as `8,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,` to be used to reference CPU IDs up to about 1000.

Even with this trick it is impossible to express things like "all even numbered CPUs with ID below 128". So yes, we should do something about it sooner or later.

**Comment by JoelColledge** [comment]
Fixed for now with e404ad96a5171c5ad7cc0d0ba5c6bbcf5d4e7a73. See the commit message for details.
