### ISSUE TITLE
drbdadm cannot work using the IP address as hostname 

### ISSUE THREAD

**Issue by little-guy-lxr** [LINBIT/drbd-utils#29]
https://github.com/piraeusdatastore/piraeus-operator/issues/473

**Comment by rck** [comment]
most likely this would have worked if the string would have been quoted, which would make it a bug of LINSTOR that generated the config without quotes. In this case I really think "don't use IPs as hostnames" is the real answer and there is nothing to fix. At least not in drbd-utils
